openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
    /user/getAllUser:
      post:
        description: "获取所有用户"
        response:
          "200":
            description: "查询成功"
            content:
              application/json:
                schema:
                  type: "json"
                examples:
                  success:
                    values: "{\"code\": 200,\"message\": \"查询成功\",\"data\": [{\"username\": \"小明\",\"phone\": \"123456789\"}]}"
components:
  schemas: {}