ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

database:
    mysql:
        url: jdbc:mysql://127.0.0.1:3306/keep_account
        user: root
        driver: com.mysql.cj.jdbc.Driver
        password: